<a href="https://colab.research.google.com/github/irenetobby/Assignment_1-/blob/main/Assignment_numpy_%26_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY PROBLEMS

In [8]:
import numpy as np
import pandas as pd

# Load dataset
df = pd.read_csv("auto-mpg (1).csv")

# Display basic info
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [9]:
mpg = df['mpg'].to_numpy()

mean_mpg = np.mean(mpg)
median_mpg = np.median(mpg)
std_mpg = np.std(mpg)

cars_above_25 = np.sum(mpg > 25)

mean_mpg, median_mpg, std_mpg, cars_above_25


(np.float64(23.514572864321607),
 np.float64(23.0),
 np.float64(7.806159061274433),
 np.int64(158))

In [10]:
cylinders = df['cylinders'].to_numpy()
car_names = df['car name'].to_numpy()

filtered_cars = car_names[cylinders > 6].tolist()
filtered_cars

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

In [11]:
weight = df['weight'].to_numpy()

np.percentile(weight, [25, 50, 75])


array([2223.75, 2803.5 , 3608.  ])

In [12]:
acc = df['acceleration'].to_numpy()

acc_normalized = (acc - acc.min()) / (acc.max() - acc.min())
acc_normalized


array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

In [13]:
hp = pd.to_numeric(df['horsepower'], errors='coerce').to_numpy()

hp_mean = np.nanmean(hp)
hp_filled = np.where(np.isnan(hp), hp_mean, hp)

hp_increased = hp_filled * 1.10
hp_increased


array([143.        , 181.5       , 165.        , 165.        ,
       154.        , 217.8       , 242.        , 236.5       ,
       247.5       , 209.        , 187.        , 176.        ,
       165.        , 247.5       , 104.5       , 104.5       ,
       106.7       ,  93.5       ,  96.8       ,  50.6       ,
        95.7       ,  99.        , 104.5       , 124.3       ,
        99.        , 236.5       , 220.        , 231.        ,
       212.3       ,  96.8       ,  99.        , 104.5       ,
       114.91632653, 110.        , 115.5       , 110.        ,
        96.8       , 110.        , 181.5       , 192.5       ,
       168.3       , 165.        , 198.        , 187.        ,
       192.5       , 121.        ,  79.2       , 110.        ,
        96.8       ,  94.6       ,  99.        ,  77.        ,
        83.6       ,  71.5       ,  75.9       ,  66.        ,
        77.        , 104.5       ,  88.        ,  59.4       ,
        99.        ,  94.6       , 181.5       , 192.5 

In [14]:
displacement = df['displacement'].to_numpy()
origin = df['origin'].to_numpy()

avg_displacement_europe = displacement[origin == 2].mean()
avg_displacement_europe


np.float64(109.14285714285714)

In [15]:
matrix = df[['mpg', 'horsepower', 'weight']].apply(
    pd.to_numeric, errors='coerce'
).fillna(0).to_numpy()

vector = np.array([1, 0.5, -0.2])

dot_product = matrix.dot(vector)
dot_product


array([-617.8, -641.1, -594.2, -595.6, -602.8, -754.2, -746.8, -740.9,
       -758.5, -660. , -612.6, -627.8, -662.2, -490.7, -402.9, -497.1,
       -488.3, -453.9, -355. , -318. , -465.9, -417. , -402.5, -364.3,
       -463.6, -805.5, -765.2, -760.4, -840.9, -355. , -379.8, -373.1,
       -384.2, -457.8, -619.3, -598.8, -597.4, -589.6, -745.3, -791.3,
       -740.3, -730.2, -889. , -851.2, -927.5, -519.4, -423.6, -587.4,
       -565.8, -378. , -351.6, -349.8, -345. , -291.1, -253.1, -309.8,
       -330. , -384.1, -360.2, -400.8, -416.6, -381.2, -759.3, -775.5,
       -737. , -735.3, -642.4, -811.6, -809.9, -799.2, -776.4, -398.5,
       -688.4, -741.6, -775.8, -726.4, -512.6, -442.2, -531.3, -377.3,
       -414. , -383.6, -429.7, -364.8, -349. , -719.5, -645.4, -712.1,
       -725.9, -665.4, -879.4, -804.8, -780.6, -758.4, -826.5, -865.7,
       -663.7, -553.7, -589.6, -521. , -542.2, -510.3, -341. , -913.4,
       -885.7, -832.8, -797.8, -489.8, -391.8, -423.2, -406.8, -361.8,
      

In [26]:
print(df.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')


In [29]:
model_year = df['model year'].to_numpy()
car_names = df['car name'].to_numpy()

In [30]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [32]:
top_5_cars = (
    df.sort_values('model_year', ascending=False)
      .head(5)['car_name']
)

top_5_cars


397         chevy s-10
396        ford ranger
395      dodge rampage
394          vw pickup
393    ford mustang gl
Name: car_name, dtype: object

In [38]:
model_year = df['model_year'].to_numpy()
car_names = df['car_name'].to_numpy()

sorted_indices = np.argsort(model_year)[::-1]
top_5_cars = car_names[sorted_indices][:5]

top_5_cars

array(['dodge aries se', 'pontiac phoenix', 'pontiac j2000 se hatchback',
       'chevrolet cavalier 2-door', 'chevrolet cavalier wagon'],
      dtype=object)

In [39]:
np.corrcoef(df['mpg'], df['weight'])[0, 1]

np.float64(-0.8317409332443352)

In [40]:
cyl = df['cylinders'].to_numpy()
mpg = df['mpg'].to_numpy()

mean_mpg_by_cyl = {
    c: mpg[cyl == c].mean()
    for c in np.unique(cyl)
}

mean_mpg_by_cyl

{np.int64(3): np.float64(20.55),
 np.int64(4): np.float64(29.28676470588235),
 np.int64(5): np.float64(27.366666666666664),
 np.int64(6): np.float64(19.985714285714284),
 np.int64(8): np.float64(14.963106796116506)}

PANDAS PROBLEMS

In [41]:
df.head(10)
df.shape
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model_year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [42]:
df_1975 = df[(df['model_year'] == 75) & (df['weight'] < 3000)]
df_1975[['car_name', 'weight', 'mpg']]

car_name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [43]:
df.isnull().sum()

df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)


/tmp/ipython-input-4093792354.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].median(), inplace=True)


In [44]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']

In [45]:
df.groupby('origin')['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [46]:
df.sort_values(by='mpg', ascending=False).head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model_year  origin                         car_name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050954  
324               0.030806  
247               0.033816

In [48]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)


In [49]:
summary_df = df.groupby('model_year')[['mpg', 'weight', 'horsepower']].mean()
summary_df

mpg       weight  horsepower
model_year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

In [50]:
high_mpg = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]
high_mpg.to_csv("high_mpg_cars.csv", index=False)

In [51]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[
    (df['mpg'] < Q1 - 1.5 * IQR) |
    (df['mpg'] > Q3 + 1.5 * IQR)
]

outliers[['car_name', 'mpg', 'model_year']]


car_name   mpg  model_year
322  mazda glc  46.6          80